## Velodyne model
sensor        : velodyne64

## Velodyne FoV (degree)
# horizontal/azimuth
max_ang_w     : 360
# vertical/altitude
max_ang_h     : 30

## Velodyne angular resolution (degree)

# The following aren't for a pretty image
# but accurate reconstructed pcl

# horizontal/azimuth resolution
#ang_res_x     : 0.1
# vertical/altitude resolution
#ang_res_y     : 2

# The following are for pretty image
# but inaccurate pcl

# horizontal/azimuth resolution
ang_res_x     : 0.1728
# vertical/altitude resolution
ang_res_y     : 0.33

## Velodyne min/max range
min_range     : 0.5
max_range     : 100

# pointcloud frame type
# see pcl RangeImage
laser_frame   : True

# publish an rgb image
rgb_range_img : False
